[2023-09-18T13:45:50.123+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-15T00:00:00+00:00 [queued]>
[2023-09-18T13:45:50.158+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-15T00:00:00+00:00 [queued]>
[2023-09-18T13:45:50.159+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:45:50.182+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-08-15 00:00:00+00:00
[2023-09-18T13:45:50.189+0000] {standard_task_runner.py:57} INFO - Started process 4290 to run task
[2023-09-18T13:45:50.194+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-08-15T00:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpf0o21ctd']
[2023-09-18T13:45:50.197+0000] {standard_task_runner.py:85} INFO - Job 212: Subtask task2
[2023-09-18T13:45:50.281+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-15T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:45:50.414+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-15T00:00:00+00:00'
[2023-09-18T13:45:50.420+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:45:50.423+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2"]
[2023-09-18T13:45:50.442+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:45:50.444+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-09-18T13:45:50.445+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-09-18T13:45:50.446+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-18T13:45:50.472+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-18T13:45:50.484+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=6.1-monitoring, task_id=task2, execution_date=20230815T000000, start_date=20230918T134550, end_date=20230918T134550
[2023-09-18T13:45:50.513+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 212 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 4290)
[2023-09-18T13:45:50.581+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:45:50.639+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-18T13:51:25.718+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-15T00:00:00+00:00 [queued]>
[2023-09-18T13:51:25.734+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-15T00:00:00+00:00 [queued]>
[2023-09-18T13:51:25.735+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:51:25.755+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-08-15 00:00:00+00:00
[2023-09-18T13:51:25.762+0000] {standard_task_runner.py:57} INFO - Started process 4629 to run task
[2023-09-18T13:51:25.768+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-08-15T00:00:00+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpr9mtxt6_']
[2023-09-18T13:51:25.769+0000] {standard_task_runner.py:85} INFO - Job 284: Subtask task2
[2023-09-18T13:51:25.839+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-15T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:51:25.929+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-15T00:00:00+00:00'
[2023-09-18T13:51:25.932+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:51:25.934+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2'"]
[2023-09-18T13:51:25.946+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:51:27.951+0000] {subprocess.py:93} INFO - Task 2
[2023-09-18T13:51:27.952+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-18T13:51:27.978+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=6.1-monitoring, task_id=task2, execution_date=20230815T000000, start_date=20230918T135125, end_date=20230918T135127
[2023-09-18T13:51:28.033+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-18T13:51:28.201+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
