[2023-09-18T13:45:45.998+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-13T00:00:00+00:00 [queued]>
[2023-09-18T13:45:46.041+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-13T00:00:00+00:00 [queued]>
[2023-09-18T13:45:46.044+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:45:46.083+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-08-13 00:00:00+00:00
[2023-09-18T13:45:46.090+0000] {standard_task_runner.py:57} INFO - Started process 4271 to run task
[2023-09-18T13:45:46.097+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-08-13T00:00:00+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmputvnqxfe']
[2023-09-18T13:45:46.099+0000] {standard_task_runner.py:85} INFO - Job 206: Subtask task2
[2023-09-18T13:45:46.190+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-13T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:45:46.349+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-13T00:00:00+00:00'
[2023-09-18T13:45:46.374+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:45:46.376+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2"]
[2023-09-18T13:45:46.400+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:45:46.441+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-09-18T13:45:46.442+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-09-18T13:45:46.443+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-18T13:45:46.462+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-18T13:45:46.482+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=6.1-monitoring, task_id=task2, execution_date=20230813T000000, start_date=20230918T134546, end_date=20230918T134546
[2023-09-18T13:45:46.506+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 206 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 4271)
[2023-09-18T13:45:46.551+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:45:46.651+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-18T13:51:23.946+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-13T00:00:00+00:00 [queued]>
[2023-09-18T13:51:23.962+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-13T00:00:00+00:00 [queued]>
[2023-09-18T13:51:23.963+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:51:23.984+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-08-13 00:00:00+00:00
[2023-09-18T13:51:23.991+0000] {standard_task_runner.py:57} INFO - Started process 4619 to run task
[2023-09-18T13:51:23.997+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-08-13T00:00:00+00:00', '--job-id', '281', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpc9izww0n']
[2023-09-18T13:51:24.001+0000] {standard_task_runner.py:85} INFO - Job 281: Subtask task2
[2023-09-18T13:51:24.113+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-13T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:51:24.300+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-13T00:00:00+00:00'
[2023-09-18T13:51:24.323+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:51:24.324+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2'"]
[2023-09-18T13:51:24.344+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:51:26.357+0000] {subprocess.py:93} INFO - Task 2
[2023-09-18T13:51:26.358+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-18T13:51:26.389+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=6.1-monitoring, task_id=task2, execution_date=20230813T000000, start_date=20230918T135123, end_date=20230918T135126
[2023-09-18T13:51:26.425+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-18T13:51:26.456+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
