[2023-09-14T13:12:30.121+0000] {processor.py:157} INFO - Started process (PID=34) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:12:30.126+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:12:30.140+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:12:30.139+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:12:30.167+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:12:30.162+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:12:30.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:12:30.233+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.123 seconds
[2023-09-14T13:13:00.574+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:13:00.587+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:13:00.595+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:13:00.591+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:13:00.633+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:13:00.618+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:13:00.634+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:13:00.676+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.109 seconds
[2023-09-14T13:13:30.774+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:13:30.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:13:30.777+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:13:30.777+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:13:30.798+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:13:30.797+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:13:30.799+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:13:30.831+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2023-09-14T13:14:00.952+0000] {processor.py:157} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:14:00.953+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:14:00.956+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:14:00.955+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:14:00.975+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:14:00.974+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:14:00.975+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:14:00.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.049 seconds
[2023-09-14T13:14:31.183+0000] {processor.py:157} INFO - Started process (PID=66) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:14:31.184+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:14:31.186+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:14:31.186+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:14:31.204+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:14:31.203+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:14:31.205+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:14:31.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2023-09-14T13:15:01.376+0000] {processor.py:157} INFO - Started process (PID=74) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:15:01.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:15:01.380+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:15:01.380+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:15:01.406+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:15:01.405+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:15:01.407+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:15:01.430+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.058 seconds
[2023-09-14T13:15:31.596+0000] {processor.py:157} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:15:31.598+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:15:31.600+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:15:31.600+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:15:31.619+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:15:31.618+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:15:31.620+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:15:31.642+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.049 seconds
[2023-09-14T13:16:01.836+0000] {processor.py:157} INFO - Started process (PID=90) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:16:01.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:16:01.840+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:16:01.839+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:16:01.861+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:16:01.860+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:16:01.862+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:16:01.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
[2023-09-14T13:16:32.031+0000] {processor.py:157} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:16:32.032+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:16:32.035+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:16:32.035+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:16:32.055+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:16:32.053+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:16:32.056+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:16:32.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2023-09-14T13:17:02.227+0000] {processor.py:157} INFO - Started process (PID=107) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:17:02.228+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:17:02.230+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:17:02.230+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:17:02.250+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:17:02.249+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:17:02.251+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:17:02.272+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2023-09-14T13:17:32.503+0000] {processor.py:157} INFO - Started process (PID=116) to work on /opt/airflow/dags/dag.py
[2023-09-14T13:17:32.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-09-14T13:17:32.858+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:17:32.857+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-09-14T13:17:32.877+0000] {logging_mixin.py:151} INFO - [2023-09-14T13:17:32.876+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 1
    from airflow import from airflow import DAG
                        ^
SyntaxError: invalid syntax
[2023-09-14T13:17:32.878+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-09-14T13:17:32.898+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.398 seconds
