[2023-09-18T13:45:48.675+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-16T00:00:00+00:00 [queued]>
[2023-09-18T13:45:48.696+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-16T00:00:00+00:00 [queued]>
[2023-09-18T13:45:48.697+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:45:48.728+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-08-16 00:00:00+00:00
[2023-09-18T13:45:48.743+0000] {standard_task_runner.py:57} INFO - Started process 4282 to run task
[2023-09-18T13:45:48.749+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-08-16T00:00:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmppgyn50wo']
[2023-09-18T13:45:48.751+0000] {standard_task_runner.py:85} INFO - Job 208: Subtask task2
[2023-09-18T13:45:48.862+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-16T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:45:49.035+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-16T00:00:00+00:00'
[2023-09-18T13:45:49.039+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:45:49.041+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2"]
[2023-09-18T13:45:49.060+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:45:49.066+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-09-18T13:45:49.067+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-09-18T13:45:49.068+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-18T13:45:49.089+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-18T13:45:49.100+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=6.1-monitoring, task_id=task2, execution_date=20230816T000000, start_date=20230918T134548, end_date=20230918T134549
[2023-09-18T13:45:49.134+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 208 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 4282)
[2023-09-18T13:45:49.166+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:45:49.214+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-18T13:51:25.900+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-16T00:00:00+00:00 [queued]>
[2023-09-18T13:51:25.911+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-16T00:00:00+00:00 [queued]>
[2023-09-18T13:51:25.912+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:51:25.932+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-08-16 00:00:00+00:00
[2023-09-18T13:51:25.939+0000] {standard_task_runner.py:57} INFO - Started process 4632 to run task
[2023-09-18T13:51:25.943+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-08-16T00:00:00+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmp6wy0pe1b']
[2023-09-18T13:51:25.945+0000] {standard_task_runner.py:85} INFO - Job 285: Subtask task2
[2023-09-18T13:51:26.003+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-16T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:51:26.088+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-16T00:00:00+00:00'
[2023-09-18T13:51:26.089+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:51:26.090+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2'"]
[2023-09-18T13:51:26.101+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:51:28.106+0000] {subprocess.py:93} INFO - Task 2
[2023-09-18T13:51:28.107+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-18T13:51:28.161+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=6.1-monitoring, task_id=task2, execution_date=20230816T000000, start_date=20230918T135125, end_date=20230918T135128
[2023-09-18T13:51:28.209+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-18T13:51:28.276+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
