[2023-09-18T13:47:16.920+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-09-12T00:00:00+00:00 [queued]>
[2023-09-18T13:47:16.934+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-09-12T00:00:00+00:00 [queued]>
[2023-09-18T13:47:16.935+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:47:16.954+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-09-12 00:00:00+00:00
[2023-09-18T13:47:16.962+0000] {standard_task_runner.py:57} INFO - Started process 4467 to run task
[2023-09-18T13:47:16.967+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-09-12T00:00:00+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmp7we1egjv']
[2023-09-18T13:47:16.969+0000] {standard_task_runner.py:85} INFO - Job 256: Subtask task2
[2023-09-18T13:47:17.031+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-09-12T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:47:17.153+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-12T00:00:00+00:00'
[2023-09-18T13:47:17.155+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:47:17.156+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2"]
[2023-09-18T13:47:17.173+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:47:17.177+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-09-18T13:47:17.178+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-09-18T13:47:17.179+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-18T13:47:17.196+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-18T13:47:17.201+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=6.1-monitoring, task_id=task2, execution_date=20230912T000000, start_date=20230918T134716, end_date=20230918T134717
[2023-09-18T13:47:17.220+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 256 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 4467)
[2023-09-18T13:47:17.260+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:47:17.298+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-18T14:06:26.000+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-09-12T00:00:00+00:00 [queued]>
[2023-09-18T14:06:26.037+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-09-12T00:00:00+00:00 [queued]>
[2023-09-18T14:06:26.038+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T14:06:26.075+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-09-12 00:00:00+00:00
[2023-09-18T14:06:26.087+0000] {standard_task_runner.py:57} INFO - Started process 5582 to run task
[2023-09-18T14:06:26.095+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-09-12T00:00:00+00:00', '--job-id', '488', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpfvfnw6e3']
[2023-09-18T14:06:26.111+0000] {standard_task_runner.py:85} INFO - Job 488: Subtask task2
[2023-09-18T14:06:26.229+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-09-12T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T14:06:26.479+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-12T00:00:00+00:00'
[2023-09-18T14:06:26.484+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T14:06:26.491+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2'"]
[2023-09-18T14:06:26.530+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T14:06:28.561+0000] {subprocess.py:93} INFO - Task 2
[2023-09-18T14:06:28.562+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-18T14:06:28.615+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=6.1-monitoring, task_id=task2, execution_date=20230912T000000, start_date=20230918T140626, end_date=20230918T140628
[2023-09-18T14:06:28.699+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-18T14:06:28.760+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
