[2023-09-18T13:45:49.654+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-14T00:00:00+00:00 [queued]>
[2023-09-18T13:45:49.726+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-14T00:00:00+00:00 [queued]>
[2023-09-18T13:45:49.730+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:45:49.773+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-08-14 00:00:00+00:00
[2023-09-18T13:45:49.786+0000] {standard_task_runner.py:57} INFO - Started process 4288 to run task
[2023-09-18T13:45:49.793+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-08-14T00:00:00+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpzwss1yyt']
[2023-09-18T13:45:49.814+0000] {standard_task_runner.py:85} INFO - Job 211: Subtask task2
[2023-09-18T13:45:49.922+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-14T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:45:50.044+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-14T00:00:00+00:00'
[2023-09-18T13:45:50.048+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:45:50.050+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2"]
[2023-09-18T13:45:50.064+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:45:50.066+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-09-18T13:45:50.066+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-09-18T13:45:50.067+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-18T13:45:50.084+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-18T13:45:50.092+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=6.1-monitoring, task_id=task2, execution_date=20230814T000000, start_date=20230918T134549, end_date=20230918T134550
[2023-09-18T13:45:50.110+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 211 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 4288)
[2023-09-18T13:45:50.149+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:45:50.203+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-18T13:51:25.543+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-14T00:00:00+00:00 [queued]>
[2023-09-18T13:51:25.562+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-14T00:00:00+00:00 [queued]>
[2023-09-18T13:51:25.563+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:51:25.612+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-08-14 00:00:00+00:00
[2023-09-18T13:51:25.618+0000] {standard_task_runner.py:57} INFO - Started process 4628 to run task
[2023-09-18T13:51:25.623+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-08-14T00:00:00+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpug1sxr3i']
[2023-09-18T13:51:25.625+0000] {standard_task_runner.py:85} INFO - Job 283: Subtask task2
[2023-09-18T13:51:25.694+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-14T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:51:25.797+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-14T00:00:00+00:00'
[2023-09-18T13:51:25.802+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:51:25.803+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2'"]
[2023-09-18T13:51:25.820+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:51:27.825+0000] {subprocess.py:93} INFO - Task 2
[2023-09-18T13:51:27.826+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-18T13:51:27.860+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=6.1-monitoring, task_id=task2, execution_date=20230814T000000, start_date=20230918T135125, end_date=20230918T135127
[2023-09-18T13:51:27.889+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-18T13:51:27.919+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
