[2023-09-18T13:46:31.156+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-31T00:00:00+00:00 [queued]>
[2023-09-18T13:46:31.174+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-31T00:00:00+00:00 [queued]>
[2023-09-18T13:46:31.175+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:46:31.193+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-08-31 00:00:00+00:00
[2023-09-18T13:46:31.200+0000] {standard_task_runner.py:57} INFO - Started process 4386 to run task
[2023-09-18T13:46:31.205+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-08-31T00:00:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpfndtnx56']
[2023-09-18T13:46:31.207+0000] {standard_task_runner.py:85} INFO - Job 236: Subtask task2
[2023-09-18T13:46:31.279+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-31T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:46:31.391+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-31T00:00:00+00:00'
[2023-09-18T13:46:31.393+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:46:31.395+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2"]
[2023-09-18T13:46:31.409+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:46:31.411+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-09-18T13:46:31.412+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-09-18T13:46:31.412+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-18T13:46:31.425+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-18T13:46:31.430+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=6.1-monitoring, task_id=task2, execution_date=20230831T000000, start_date=20230918T134631, end_date=20230918T134631
[2023-09-18T13:46:31.449+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 236 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 4386)
[2023-09-18T13:46:31.459+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T13:46:31.490+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-18T13:52:30.363+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-31T00:00:00+00:00 [queued]>
[2023-09-18T13:52:30.401+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-31T00:00:00+00:00 [queued]>
[2023-09-18T13:52:30.403+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T13:52:30.442+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2023-08-31 00:00:00+00:00
[2023-09-18T13:52:30.455+0000] {standard_task_runner.py:57} INFO - Started process 4917 to run task
[2023-09-18T13:52:30.481+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '6.1-monitoring', 'task2', 'scheduled__2023-08-31T00:00:00+00:00', '--job-id', '360', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmp9vu97575']
[2023-09-18T13:52:30.485+0000] {standard_task_runner.py:85} INFO - Job 360: Subtask task2
[2023-09-18T13:52:30.695+0000] {task_command.py:415} INFO - Running <TaskInstance: 6.1-monitoring.task2 scheduled__2023-08-31T00:00:00+00:00 [running]> on host e891a57bf0af
[2023-09-18T13:52:31.012+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1-monitoring' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-31T00:00:00+00:00'
[2023-09-18T13:52:31.016+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-18T13:52:31.019+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'Task 2'"]
[2023-09-18T13:52:31.068+0000] {subprocess.py:86} INFO - Output:
[2023-09-18T13:52:33.083+0000] {subprocess.py:93} INFO - Task 2
[2023-09-18T13:52:33.084+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-18T13:52:33.118+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=6.1-monitoring, task_id=task2, execution_date=20230831T000000, start_date=20230918T135230, end_date=20230918T135233
[2023-09-18T13:52:33.164+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-18T13:52:33.272+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
